### ISSUE TITLE
May you release your trained generator

### ISSUE THREAD

**Issue by xujli** [xiaoxingxingkz/TPA-GAN#1]
May you release your trained generator

**Comment by xiaoxingxingkz** [comment]
The pre-trained task-induced discriminator can help the generator get an ideal result. The  pre-trained task-induced discriminator got a result of TrainACC0.9271_TestACC0.8875_TestSEN0.8958_TestSPE0.8811_TestAUC0.9518, and the generator can reach: TrainACC0.9844_TestACC0.7933_TestSEN0.8611_TestSPE0.7405_TestAUC0.8852. The trained generator has been uploaded to ./Generator_save/ I am not sure it can fit the latest version for a few changes about the network. And there are two ways for improvement: 1. initialize the image domain to 0-1; 2. train the model repeatedly.

**Comment by xujli** [comment]
Thanks for your advice, I'll try it. I trained it without TA and get ssim=0.55. And if it's convenient for you to share the weights of trained Generator.

**Comment by xiaoxingxingkz** [comment]
Share the TA model? this training is easy to achieve when you add the SSIM loss into the generator losses.

**Comment by xujli** [comment]
I just train GAN only containing G and D, what else should I change except removing TA.

**Comment by xiaoxingxingkz** [comment]
I do not understand your purpose clearly, do you want to achieve the best performance?  if you want to improve, the generation_loss can contain SSIM, L1 and L2. Generally, there is only L1 loss.

**Comment by xujli** [comment]
英文太烂。我就是问两个事情，一个是我把TA去了只训练G和D，除了删掉TA对应的代码外，还需要调整什么吗，上次直接跑训练出来的SSIM只有0.55，感觉太低了。另外一个是方不方便把你训练好的Generator权重分享一下。

**Comment by xiaoxingxingkz** [comment]
把SSIM加到损失函数里，结果就不会低了。





------------------ Original ------------------
From: xujing li ***@***.***&gt;
Date: Wed,Aug 17,2022 7:36 PM
To: xiaoxingxingkz/TPA-GAN ***@***.***&gt;
Cc: xiaoxingxingkz ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [xiaoxingxingkz/TPA-GAN] May you release your trained generator(Issue #1)





 
英文太烂。我就是问两个事情，一个是我把TA去了只训练G和D，除了删掉TA对应的代码外，还需要调整什么吗，上次直接跑训练出来的SSIM只有0.55，感觉太低了。另外一个是方不方便把你训练好的Generator权重分享一下。

**Comment by xujli** [comment]
我看cirterion_ssim在generator loss里，我把数据归一化后再试试，这个归一化的话，是每个sample自己做0-1归一化，还是所有数据取最大最小来做0-1归一化

**Comment by xiaoxingxingkz** [comment]
基于每个被试归一化





------------------ Original ------------------
From: xujing li ***@***.***&gt;
Date: Wed,Aug 17,2022 7:42 PM
To: xiaoxingxingkz/TPA-GAN ***@***.***&gt;
Cc: xiaoxingxingkz ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [xiaoxingxingkz/TPA-GAN] May you release your trained generator(Issue #1)





 
我看cirterion_ssim在generator loss里，我把数据归一化后再试试，这个归一化的话，是每个sample自己做0-1归一化，还是所有数据取最大最小来做0-1归一化

**Comment by xujli** [comment]
好滴，非常感谢（英文还需要锻炼）

**Comment by xiaoxingxingkz** [comment]
我的英文也很水，能交流就行😄😂





------------------ Original ------------------
From: xujing li ***@***.***&gt;
Date: Wed,Aug 17,2022 7:50 PM
To: xiaoxingxingkz/TPA-GAN ***@***.***&gt;
Cc: xiaoxingxingkz ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [xiaoxingxingkz/TPA-GAN] May you release your trained generator(Issue #1)





 
好滴，非常感谢（英文还需要锻炼）

**Comment by xujli** [comment]
我在我的repo里传了一个基于你的代码，没有task classifier的GAN，修改的地方很少，你能帮我看一下有什么问题吗。我训练四百多epoch下来的SSIM只有0.7，而且我在训练的时候做了归一化，在test反而没有归一化的输入SSIM更高

**Comment by xiaoxingxingkz** [comment]
你的图像尺寸跟我一样大的吗？不会吧，我随便一训都0.9几。





------------------ Original ------------------
From: xujing li ***@***.***&gt;
Date: Sat,Aug 20,2022 9:48 AM
To: xiaoxingxingkz/TPA-GAN ***@***.***&gt;
Cc: xiaoxingxingkz ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [xiaoxingxingkz/TPA-GAN] May you release your trained generator (Issue #1)





 
我在我的repo里传了一个基于你的代码，没有task classifier的GAN，修改的地方很少，你能帮我看一下有什么问题吗。我训练四百多epoch下来的SSIM只有0.7，而且我在训练的时候做了归一化，在test反而没有归一化的输入SSIM更高

**Comment by xujli** [comment]
我用的是你的那个pipeline那个repo运行出来做的数据，只是把里面bash命令用python的os.system执行的。

**Comment by xujli** [comment]
要不然我发你两个做出来的sample你看一下

**Comment by xujli** [comment]
对不起，好像是我计算SSIM调用的是计算SSIM loss的模块

**Comment by tantantan007** [comment]
> 对不起，好像是我计算SSIM调用的是计算SSIM loss的模块

兄弟，你跑出来了吗？我有一些问题
