### ISSUE TITLE
Data release?

### ISSUE THREAD

**Issue by aldiak** [xiaoxingxingkz/TPA-GAN#2]
Greetings Sir, I would like to know if you could possibly release your processed data thanks.

**Comment by xiaoxingxingkz** [comment]
Sorry about that, the author has a limitation to sharing original or processed data according to ADNI protocol.

**Comment by xiaoxingxingkz** [comment]
Sorry about that, the author has a limitation to sharing original or processed data according to ADNI protocol.

**Comment by aldiak** [comment]
Okay. Can you share the pipeline or script used for preprocessing? Thanks

**Comment by xiaoxingxingkz** [comment]
You can see my next repository. Link: https://github.com/xiaoxingxingkz/MRI-and-PET-data-from-ADNI

**Comment by aldiak** [comment]
Awesome, thanks!
