### ISSUE TITLE
如何转换mat格式

### ISSUE THREAD

**Issue by tantantan007** [xiaoxingxingkz/TPA-GAN#3]
你好，我经过您的预处理步骤的是时候，发现nii格式转mat后，模型训练不了，能告诉转mat的详细步骤吗？

**Comment by tantantan007** [comment]
已经解决了，原来还需要一步，将两个三维数据变成四维数据

**Comment by xiaoxingxingkz** [comment]
好的，👍





------------------ 原始邮件 ------------------
发件人: tantantan007 ***@***.***&gt;
发送时间: 2024年4月8日 16:53
收件人: xiaoxingxingkz/TPA-GAN ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [xiaoxingxingkz/TPA-GAN] 如何转换mat格式 (Issue #3)





 
已经解决了，原来还需要一步，将两个三维数据变成四维数据
